service: LambdaTeam

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  memorySize: 128
  timeout: 10
  versionFunctions: false

functions:
  getStarted:
    handler: src/handlers/getStarted.handler
    events:
      - http:
          method: GET
          path: /name

plugins:
  - serverless-plugin-typescript
