service: LambdaTeam

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  memorySize: 128
  timeout: 10
  versionFunctions: false
  environment:
    AWS_COGNITO_CLIENT_ID: 38ccodrt0knar0soc0kqubf16u

functions:
  getStarted:
    handler: src/handlers/getStarted.handler
    events:
      - http:
          method: GET
          path: /name
  register:
    handler: src/handlers/register.handler
    events:
      - http:
          method: POST
          path: /register
          request:
            schemas:
              application/json: ${file(schemas/register.json)}
  autoVerify:
    handler:  src/handlers/auto-verify.handler
  

plugins:
  - serverless-plugin-typescript
