name: Test main-tasks

on:
  push:
    branches: [main]
    paths: 
      - 'main-tasks/**'
  pull_request:
    branches: [main]
    paths: 
      - 'main-tasks/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
        env:
          MONGODB_URL: mongodb://localhost:27017
          JWT_TOKEN_KEY: 'Slava Ukraine'
          JWT_REFRESH_TOKEN_KEY: 'Heroyam Slava'
